### ISSUE TITLE
.app file missing for MacOS in the zip file

### ISSUE THREAD

**Issue by siva-mudiyanur** [zacharee/ArcadyanKVD21Control#1]
I'm unable to find the .app file for MacOS in the zip file as per the instructions.

Thank you for creating this application!

**Comment by zacharee** [comment]
1.2.0 just finished building. Check again for the macOS files:
<img width="827" alt="image" src="https://github.com/zacharee/ArcadyanKVD21Control/assets/9020352/c15ba16f-d549-470c-a340-e3bf41074ef7">

**Comment by siva-mudiyanur** [comment]
Got it, thanks! my mac is running on intel chip with Monterey version 12.6.5. Neither of the apps appear to be supported for my mac.

**Comment by zacharee** [comment]
The amd64 is for Intel Macs.

Zachary Wander
