### ISSUE TITLE
Signal Graphs

### ISSUE THREAD

**Issue by zacharee** [zacharee/ArcadyanKVD21Control#10]
Having some sort of graph that can record data points of signal on every refresh would be helpful.

Right now, there don't seem to be any Compose Multiplatform graphing libraries that target Android, JVM, and iOS, so this isn't currently possible without trying to make an intermediate adapter for multiple libraries.

**Comment by deilert00** [comment]
How about logging to csv - especially in the desktop environments.  We could create our own from there.
