### ISSUE TITLE
Hidden network?

### ISSUE THREAD

**Issue by jpettitt** [zacharee/ArcadyanKVD21Control#11]
I've noticed that even with both bands disabled I'm still seeing a hidden network every couple of minutes, som times on 2.4GHz sometimes on 5GHz.  Any idea what it is or how to make it go away?  (screen shot from Wifi Explorer Pro on a Mac)
<img width="1458" alt="image" src="https://github.com/zacharee/ArcadyanKVD21Control/assets/524856/af4326b3-4b0f-4db0-9b0b-e579a963e92f">

**Comment by zacharee** [comment]
This seems to be a bug in the firmware. I don't think there's a way for me to fix it.
