### ISSUE TITLE
Reboot based on Band change (or parameter)

### ISSUE THREAD

**Issue by deilert00** [zacharee/ArcadyanKVD21Control#12]
I'm having a lot of issues with T-Mo services, and this app does help.  If I'm having network issues, I quickly look at the app to (1) see what tower I'm on [ECGI Value] and (2) what band I'm on.  If ECGI <> x, reboot.  If [BAND = B2] reboot or if [BAND <> B66] reboot.  Essentially, this is what I do manually to correct the tower or band issue, typically a single reboot gets me back into an "acceptable" level.  What do you think?

**Comment by f1vefour** [comment]
You would definitely need the ability to disable after X amount of reboots or it could  put the router into an artificial boot loop.

**Comment by zacharee** [comment]
Closing in favor of #56
