### ISSUE TITLE
TestFlight version not updated

### ISSUE THREAD

**Issue by jgleigh** [zacharee/ArcadyanKVD21Control#14]
The version available on TestFlight is stuck at 1.6.0.

**Comment by zacharee** [comment]
Apple is very intent on not properly testing the uploads and rejecting them, and I'm currently unable to upload a new build because they haven't allowed uploads from the latest version of Xcode: https://developer.apple.com/forums/thread/734618.

**Comment by jgleigh** [comment]
Sorry to hear that. I'm running the macOS version too so really just wanted to make sure I wasn't missing something on iOS.
