### ISSUE TITLE
Error on channel selection 

### ISSUE THREAD

**Issue by obsanity** [zacharee/ArcadyanKVD21Control#17]
I'm getting an error for certain channels as well as wrong channel reporting for some (last=previously reported). Also, all manual selections seems to default to 20Mhz channel. Auto selection throws is on 80Mhz. I'm on Sagemcom Fast 5688W hardware 1.0 Software SGJi10203-1.2.90. Here are my testing for 5Ghz frequency:

32 - error
36 - good 20Mhz report last, shows on Ch40
40 - good 20Mhz report last, shows on Ch40
44 - good 20Mhz
48 - good 20Mhz report last, shows on Ch48
52 - good 20Mhz
56 - good 20Mhz
60 - good 20Mhz
64 - good 20Mhz
68 - error
96 - error
100 - good 20Mhz
104 - good 20Mhz
108 - good 20Mhz
112 - good 20Mhz
116 - good 20Mhz
120 - good 20Mhz
124 - good 20Mhz report last, shows on Ch124
128 - good 20Mhz
132 - good 20Mhz
136 - good 20Mhz
140 - good 20Mhz
144 - good 20Mhz
149 - good 20Mhz
153 - good 20Mhz report last, shows on Ch153
157 - good 20Mhz report last, shows on Ch157
161 - good 20Mhz report last, shows on Ch161
165 - good 20Mhz report last, shows on Ch165

This is the error I get(***** sensitive data removed)

Bad Request
{status==400
headers==[content-length=[95],date=[Sun, 03 Sep 2023 18:55:19 GMT],server=[lighttpd/1.4.59]]
requestHeaders==[Authorization=[Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTM3Njc2MDgsImlhdCI6MTY5Mzc2NjcwOCwicmVmcmVzaENvdW50TG**************vdW50TWF4Ijo0fQ.wDPEFAWy39tZFdBIplrxntjB4mbbXfHU04NSOfAQrCE],Accept=[application/json],Accept-Charset=[UTF-8]]
requestBody=={"2.4ghz":{"airtimeFairness":true,"channel":"Auto","channelBandwidth":"Auto","isMUMIMOEnabled":true,"isRadioEnabled":false,"isWMMEnabled":true,"maxClients":128,"mode":"auto","transmissionPower":"100%"},"5.0ghz":{"airtimeFairness":true,"channel":"32","channelBandwidth":"Auto","isMUMIMOEnabled":true,"isRadioEnabled":true,"isWMMEnabled":true,"maxClients":128,"mode":"auto","transmissionPower":"100%"},"bandSteering":{"isEnabled":true},"ssids":[{"2.4ghzSsid":false,"5.0ghzSsid":true,"encryptionMode":"AES","encryptionVersion":"WPA2/WPA3","guest":false,"isBroadcastEnabled":true,"ssidName":"********","wpaKey":"********","canEditFrequencyAndGuest":true,"ssidId":null,"enabled":null}],"canAddAndRemove":true}
requestUrl==http://192.168.12.1/TMI/v1/network/configuration/v2?set=ap
requestMethod==POST}
{"result":{"statusCode":400,"error":"BadRequest","message":"No query specified or bad params"}}

Let me know if you'd like to test 2.4Ghz like this.

**Comment by zacharee** [comment]
I can't reproduce the bandwidth drop on the Arcadyan. It seems to stay at 80MHz for any band. I can add a bandwidth selector option, which works on the Arcadyan at least, to try to force the one you want.

I'm going to remove those bands that error out since they're ones that aren't used or the gateway doesn't support.

**Comment by obsanity** [comment]
Got 1.9 and it works as expected. However for some reason channel 165 with anything above 20Mhz will not broadcast a signal at all. It actually takes the setting but does not show signal. Also, consider graying out these settings if radio is off. Initially I tried these without enabling and was getting that error. Obviously radio has to be on first.

**Comment by zacharee** [comment]
On the Arcadyan, 165 supports all bandwidths and accepts changes when the radios are disabled. Since it's not really that simple to tell them apart through the API, I'm going to keep it as-is.
