### ISSUE TITLE
Nokia fastmile gateway 3.2 

### ISSUE THREAD

**Issue by poriyakey** [zacharee/ArcadyanKVD21Control#20]
Please fix Error for 
Nokia fastmile gateway 3.2 
![Screenshot_20230917_012007_Gallery](https://github.com/zacharee/ArcadyanKVD21Control/assets/125101780/13f598fb-f001-4f16-bd26-44e32326981a)
![Screenshot_20230917_012000_Gallery](https://github.com/zacharee/ArcadyanKVD21Control/assets/125101780/0a3ac9ae-2eb9-4ad0-a093-b76be2d62fb2)

**Comment by zacharee** [comment]
This app is only meant for the gateways provided by T-Mobile, which use specific APIs.

**Comment by poriyakey** [comment]
Please fix gateway 3.2 😔

**Comment by zacharee** [comment]
There isn't anything to fix. This app is specifically for T-Mobile Home Internet gateways, and the FastMile 3.2 isn't a T-Mobile Home Internet gateway.
