### ISSUE TITLE
Enable P2P On KVD21

### ISSUE THREAD

**Issue by MickeyDAZ** [zacharee/ArcadyanKVD21Control#21]
I'm beginning to use Apple Home, and I'm connecting 2 HomePod Minis (Trying to)

When I reach end of configuration using Home App on iOS, I get a warning that some features will not be enabled without router (KVD21 Gateway) having Peer-to-Peer enabled.

Does KVD21 have P2P feature that you can access, and can be enabled using HINT Control?

**Comment by zacharee** [comment]
Apple isn't really clear about what they mean by "peer-to-peer" connections. Unless you've created a guest network to connect them to, there shouldn't be any client isolation, and multicast DNS should be enabled by default.
