### ISSUE TITLE
"HINT Control is no longer available" -- iPhone issue

### ISSUE THREAD

**Issue by david03w** [zacharee/ArcadyanKVD21Control#22]
I'm sure this isn't an app issue, and it's an issue with my iPhone, but I'm hoping someone knows what it means.

I got the app sideloaded successfully on my iPhone and had been using it for a week or so. 

Today I try to use it, and it says "HINT Control" is no longer available.  If this is an app I sideloaded, what does that mean?  Is this like an internal app audit part of Apple software?  Is there a way around it?  I barely figured out how to sideload it in the first place, and I've since completely forgotten how I did it :(

**Comment by david03w** [comment]
FIXED - iPhone Settings > App Store > Offload Unused Apps, turn off.  Re-sideload HINT Control app

**Comment by logicito** [comment]
Isn't easier to just use the TestFlight version?

**Comment by david03w** [comment]
you are correct!  1000x easier!  I tried TestFlight from the very beginning but got hung up on the "click on the email link" part, so I went to Sideloadly method instead.
but your comment made me go examine the TestFlight method again.  I was doing something stupid.  I was accessing github on my desktop, so when I opened the TestFlight app, there was nothing to click on, and I thought I was missing something.
but -- surprise! -- opening the github link on my phone gave TestFlight what it needed.  so thanks for making me reinvestigate this.

**Comment by logicito** [comment]
> you are correct!  1000x easier!  I tried TestFlight from the very beginning but got hung up on the "click on the email link" part, so I went to Sideloadly method instead.
> 
> but your comment made me go examine the TestFlight method again.  I was doing something stupid.  I was accessing github on my desktop, so when I opened the TestFlight app, there was nothing to click on, and I thought I was missing something.
> 
> but -- surprise! -- opening the github link on my phone gave TestFlight what it needed.  so thanks for making me reinvestigate this.

If you have a silicon mac you can run the app
