### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by BigFlubba** [zacharee/ArcadyanKVD21Control#23]
I've tried to look for myself, but my coding skills are very slim. What would be the url I can use to reboot the device? I want to have an automation that can reboot it an do simple tasks if something happens. Can this be integrated into the app or would I need to automate it myself?

**Comment by zacharee** [comment]
I can probably add a Tasker integration on Android to send a reboot command to the gateway, but I've been avoiding a feature like this since it requires the device sending the command to always be on the local network.

**Comment by BigFlubba** [comment]
Doesn't have to be. You can use Tailscale and do it that way. That's how I'm able to monitor everything even looking at my cell stats remotely outside of my network. I know this is a stretch but it would be cool if later on I could have an integration with some monitoring software to auto reboot it if it starts to do some funky things. But, that is over my head currently.

**Comment by zacharee** [comment]
Closing in favor of #56
