### ISSUE TITLE
Option to change APN on a Sagemcom Fast 5688w

### ISSUE THREAD

**Issue by tamegreentux** [zacharee/ArcadyanKVD21Control#25]
Request to change APN. Google Fi uses the T-Mobile network. I have one working with a Google Fi SIM and 
am successfully able to use HINT control to turn off the WiFi and verify connection and APN is set to "FBB.HOME"

I would like to be able to change the APN to "h2g2" to see if it makes any difference.
https://support.google.com/fi/answer/6330195?hl=en#zippy=%2Cset-up-your-device

I have tried unsuccessfully to SSH, Telnet and HTTP into some type of admin console unsuccessfully.
![PXL_20231119_022829629](https://github.com/zacharee/ArcadyanKVD21Control/assets/151420457/e50ce5de-c5c9-4e25-bed5-bffccc317427)
![PXL_20231119_022445750](https://github.com/zacharee/ArcadyanKVD21Control/assets/151420457/74dbbc13-bf58-4555-afaa-f8a4dfa388a9)

**Comment by zacharee** [comment]
Unfortunately, the API doesn't provide a way to change the APN. Someone with better reverse engineering skills than me would need to figure out if it's even possible.
