### ISSUE TITLE
Please consider adding ability to default or toggle external antenna for Arcadyan G4AR

### ISSUE THREAD

**Issue by clobberx** [zacharee/ArcadyanKVD21Control#26]
Upon reboot the Arcadyan G4AR appears to revert to internal antenna. Please add ability to default external and or toggle remotely as this setting is currently only available on the Gateway itself.

**Comment by aaronsilber** [comment]
@clobberx Are you still experiencing this? I recently tested rebooting my Arcadyan G4AR from the HINT Control app, and found it persisted the external antenna setting.

**Comment by clobberx** [comment]
@aaronsilber, you are correct. This must have been a temporary glitch. Antenna settings persist now. Thanks for the follow up!
