### ISSUE TITLE
TestFlight expired

### ISSUE THREAD

**Issue by christophermichaelshaw** [zacharee/ArcadyanKVD21Control#27]
Just a quick heads up — it appears the project TestFlight has expired. I downloaded the app and joined the flight a week or so ago, but only now have had a chance to try the application and it now reports the expiry. The link on the readme docs also confirms the expiration of the flight. 

Happy to help with any documentation or further troubleshooting! I’m excited to try the app, and I appreciate the work to build a more useful app to manage tmo home WiFi as the official app/web interface is… generously put: a waste of bits and/or bytes. 

![image](https://github.com/zacharee/ArcadyanKVD21Control/assets/65378856/6407547e-68c3-457f-8ce7-5df00af5ffa9)

![image](https://github.com/zacharee/ArcadyanKVD21Control/assets/65378856/d0d9d000-c9c3-4c4c-b83f-5a52b79798b8)

![image](https://github.com/zacharee/ArcadyanKVD21Control/assets/65378856/2642ec83-5a7c-4e3a-852f-b38d325e5800)

Relevant details:
iPhone 15 Pro Max
iOS 17.2 (21C5054b) <- Current Dev Beta 

iPad Pro w/ current general release iOS 17 (don’t have in front of me at the moment to collect the specific version).

Troubleshooting steps:
- Removed and attempted to rejoin flight. (Rebooted, rinsed and repeated). 
- Used WiFi and direct LTE connection.

**Comment by matt12eagles** [comment]
Yep! Same situation, love this app! Looking forward to getting it back

**Comment by rcuprill** [comment]
App is now available in regular Apple App Store for iOS devices.

**Comment by zacharee** [comment]
I've updated the README to link to the App Store now that it's available there.
