### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by qwackman** [zacharee/ArcadyanKVD21Control#3]
I can not find the ipa file for iOS. I am running 16.6. is there a way to install it using Altstore?

Thanks,
Qwackman

**Comment by zacharee** [comment]
It's the second file in the release: https://github.com/zacharee/ArcadyanKVD21Control/releases/download/1.2.2/HINT.Control.ipa.

You need to use AltStore or Sideloadly to install it.

**Comment by qwackman** [comment]
Thank you!
