### ISSUE TITLE
JSON Error logging into Sagemcom Fast 5688w

### ISSUE THREAD

**Issue by mackcoding** [zacharee/ArcadyanKVD21Control#31]
I'm thinking my Sagemcom Fast 5688W updated in the past few days. The app worked fine, but now I'm getting a json error:
![image](https://github.com/zacharee/ArcadyanKVD21Control/assets/10917563/ea014ffa-1de7-4919-9db5-269d7bbc9a41)

**Comment by hannbah** [comment]
Same error 2024-01-02.  Will not connect.

**Comment by mackcoding** [comment]
I believe this may be a firmware issue and not necessarily related to Hint Control. If I try to use the T-Mobile Internet application, it gets stuck in the “Let's get reconnected!” screen. When I try Hint Control, I get this error. 

@hannbah can you try the T-Mobile Internet application to see if you are also stuck in a loop?  When I try to access http://192.168.12.1/TMI/v1/gateway/?get=all it doesn't load at all — but if I browse to http://192.168.12.1/  it loads instantly. 

I'm also seeing this:
![image](https://github.com/zacharee/ArcadyanKVD21Control/assets/10917563/73229652-ef50-49f5-af50-16d4fd6fe787)

It says I'm not connected, but I very much am (it's my primary internet).

Last thing: If you check the [reviews](https://play.google.com/store/apps/details?id=com.tmobile.homeisp) you'll see people complaining of the same type of issues. 

This is my guess.

**Comment by zpifer13** [comment]
I have the Sagemcomm as well I had to downgrade the app sadly...thanks for all your hard work zacharee if I were a wealthy man i would pay you handsomely and let u hand ick a team to just crack each router wide open. This is ridiculous.... Anyways thank you  so much for all your hard work don't give up!

**Comment by zacharee** [comment]
This is maybe related to #2, but it's likely an issue with the gateway firmware.
