### ISSUE TITLE
iOS 17.2.1, HINT control 1.10.1 - can't get past login screen

### ISSUE THREAD

**Issue by sfx2000** [zacharee/ArcadyanKVD21Control#32]
on first setup - can't get past the login screen...

![IMG_3893](https://github.com/zacharee/ArcadyanKVD21Control/assets/14082805/c7e16cb2-90bd-449d-b473-e1e2ee3039d8)

**Comment by zacharee** [comment]
Are you able to dismiss the keyboard by tapping outside of a text field?

**Comment by sfx2000** [comment]
NopeOn Jan 8, 2024, at 4:23 PM, Zachary Wander ***@***.***> wrote:﻿
Are you able to dismiss the keyboard by tapping outside of a text field?

**Comment by sfx2000** [comment]
That's what I was thinking, but no, it will not get out of the way...

Should also note that there are no custom keyboards installed, so it's just the standard and emoji ones...

Pretty odd, hence the issue report

**Comment by zacharee** [comment]
1.10.2 should have better interaction with the keyboard on iOS.

**Comment by sfx2000** [comment]
Yep. keyboard input areas now work correctly - was "return" now it "go"

tested and 1.10.2 works correctly, feel free to close this issue as resolved/tested
