### ISSUE TITLE
errors turning off wifi opn tmo gear 

### ISSUE THREAD

**Issue by hamhamfreak** [zacharee/ArcadyanKVD21Control#36]
Errors wehen trying to disabl,e wifi on the tmo gear 
Request Timeout
{status==408
headers==[content-length=[132],content-type=[application/json],date=[Sat, 27 Jan 2024 00:04:18 GMT],server=[lighttpd/1.4.59]]
requestHeaders==[User-Agent=[homeisp/android/2.12.1],Authorization=[Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MDYzMTQ3MjksImV4cGlyYXRpb24iOjE3MDYzMTQ3MjksImlhdCI6MTcwNjMxMzgyOSwiaXNzIjoiMTg6YTU6ZmY6MGE6NTk6MTgiLCJyZWZyZXNoQ291bnRMZWZ0Ijo0LCJyZWZyZXNoQ291bnRNYXgiOjQsInRva2VuX2V4cGlyZSI6MzM2OSwidHlwZSI6InBhc3N3b3JkIn0.tSuZJIyNtJNfY51SxMYugJ_3LLHcJUMtsCaZBSojrpI],Accept=[application/json],Accept-Charset=[UTF-8]]
requestBody==
requestUrl==http://192.168.12.1/TMI/v1/network/configuration/v2?get=ap
requestMethod==GET}
{
  "result": {
    "error": "SetFailed",
    "message": "WiFi driver is busy. Please try again later.",
    "statusCode": 408
  }
}

**Comment by hamhamfreak** [comment]
@zacharee any ideas?

**Comment by maodijim** [comment]
> 

had this same problem, make sure all clients disconnect and try to save the setting again. That worked for me.
