### ISSUE TITLE
Feature Request - Client/Port Speed Limit Control

### ISSUE THREAD

**Issue by axmeone** [zacharee/ArcadyanKVD21Control#37]
Would it be feasible to implement bandwidth/speed limit control per client, specifically specific wired clients or even based on individual LAN ports?

I have the Arcadyan KVD21 and HINT (dev-zwander-arcadyankvd21control-23-windows-amd64.zip) from 2023-09-03.

Thank you.

**Comment by zacharee** [comment]
As far as I know, the gateways don't have any support for this.
