### ISSUE TITLE
iOS cant select in confirm windows

### ISSUE THREAD

**Issue by coldcreature** [zacharee/ArcadyanKVD21Control#40]
On iOS, when attempting to turn off wifi or reboot, popup confirmation windows are unresponsive.

Model: iphone SE
Version: 17.4

**Comment by KewlGuyRox** [comment]
I have similar issue. On save dialog it hangs and pressing Yes does nothing. Did a full reset of the gateway but it is behaving the same way.

**Comment by muhafam528** [comment]
Same issue here. Can’t confirm “yes” to complete process of disabling WiFi radios.
