### ISSUE TITLE
App crashes on launch

### ISSUE THREAD

**Issue by 95oRANGEcRUSH** [zacharee/ArcadyanKVD21Control#42]
App version 1.10.4
Sagemcom gateway
iOS 17.4.1
iPhone 14 Pro Max 

Every time I launch the app, it briefly (like, half a second) shows the login screen then crashes. I’ve rebooted my phone to the same result. Have not tried deleting/reinstalling the app. Screen recording attached. 

https://github.com/zacharee/ArcadyanKVD21Control/assets/162072547/d8ee8feb-4c89-4802-b23e-3db5f54ae3f9

**Comment by zacharee** [comment]
Does 1.10.5 work?

**Comment by 95oRANGEcRUSH** [comment]
So far, so good. Thanks!
