### ISSUE TITLE
Wifi bands permanently disabled TMOGAR4

### ISSUE THREAD

**Issue by PresidentofGenericTrade** [zacharee/ArcadyanKVD21Control#45]
![Screenshot_20240416_224438_HINT Control](https://github.com/zacharee/ArcadyanKVD21Control/assets/136501903/73c2c751-af85-4846-ae23-c7a7f8853afe)
![Screenshot_20240416_224427_HINT Control](https://github.com/zacharee/ArcadyanKVD21Control/assets/136501903/ff2aa7fa-97d4-47c5-be86-dee636e1987a)

Cannot turn on the wifi bands on TMOGAR4

**Comment by kopite88** [comment]
I have the same error.  My TMOGAR4 modem firmware was updated to 1.00.09 last week, not sure this has anything to do with it.  I was able to add a SSID, but all the 'Band Management' sliders were dead.

**Comment by marcshul** [comment]
If you turn off 5GHz Radio and enable the Hidden toggle(s)  (because you don't need 5GHz and don't want it blasting your bedroom) will you still be in contact with the gateway via 2.4GHz Radio and via the wired LAN connection?

**Comment by kopite88** [comment]
Problem solved.  Turned out that after firmware update to 1.00.09, one needs to do a factory reset to have wifi working again.

**Comment by zacharee** [comment]
You need to have an SSID added to enable WiFi or update the configuration.
