### ISSUE TITLE
Had to get new gateway from T-Mobile, can’t log in to hint 

### ISSUE THREAD

**Issue by lindsaygreen32** [zacharee/ArcadyanKVD21Control#46]
Had to replace current equipment. Reset  everything in order to reconnect my eero mesh. Now I cannot log in with HINT. I get this message.  Am I missing something? 
![IMG_0026](https://github.com/zacharee/ArcadyanKVD21Control/assets/170210006/d8ce7c17-0eca-4cfe-b9c7-e835b45e1cc9)

**Comment by zacharee** [comment]
Duplicate of #2
