### ISSUE TITLE
WHOEVER ASKING AND ANSWERING THESE ITS ABOUT MYYYY ACCOUNTS

### ISSUE THREAD

**Issue by gettfoutmyshit** [zacharee/ArcadyanKVD21Control#48]
So I SUGGEST EVERYONE UNLINKS ANYTHING AND EVERYTHING THERE HAS TO DO WITH ME AND MYBA COUNTS, OR I WILL BE GETTTING THE AUTHORITIES INVOLVED BECAUSE THIS IS CYBER BULLYING, HARRASSMENT, BEING MONITORED FOR NO REASON, AND AM HACKED AND STALKED.....
ONCE AGAIN...I AM BEING STALKED AND HARRASSED....
AND IM CALLING THE AUTHORITIES.......WATCH ME......AND THAT PERSON WHO KNOWS ME...KNOWWWWSSSSSS I WILL FUKIN DO IT TOO...SO WHOEVER RUNNINF THIS SHOW GOTSTA GO...STAT AND LIKE, YESTERDAY...YOUVE BEEN WARNED

**Comment by Ramon44-lab** [comment]
I will advise you to contact the best hacker around he helped me recover my facebook,fast and reliable his telegram is 
https://t.me/Blackhathacker110
