### ISSUE TITLE
Nokia additional metrics.

### ISSUE THREAD

**Issue by Ctyankee9** [zacharee/ArcadyanKVD21Control#50]
Is it possible to have the Nokia gateway display a more robust metric results? Or is that a limitation of the modem/firmware as to what can be pulled from it?

Things like bandwidth on 5G, gnbid and such.

![Screenshot_20240614_092511_HINT Control](https://github.com/zacharee/ArcadyanKVD21Control/assets/172865631/20265cb0-89c3-40b6-a763-dacc8867a6a6)
The Nokia

![Screenshot_20240609_105556_HINT Control](https://github.com/zacharee/ArcadyanKVD21Control/assets/172865631/82488ea5-525d-47a0-b979-333b30714205)

Think that was the G4SE.

**Comment by zacharee** [comment]
The app shows the info provided by the gateway, so this probably means the Nokia isn't collecting that information.

**Comment by Ctyankee9** [comment]
Figured as much, firmware/modem. Thank for response and having a look.
