### ISSUE TITLE
Suggestions for managing Wifi connections

### ISSUE THREAD

**Issue by ejgoldstick** [zacharee/ArcadyanKVD21Control#53]
Testing a Nokia 5G21 or the TMO-G4AR with the Wifi turned off has a positive impact on performance

1) a single toggle to turn all WIFI off or on for the gateway being monitored 

2) a refresh button for the devices connected at any given moment

- devices seem to get stuck in "Connected true" even when both 2.4 GHz and 5 GHz Wifi have been deactivated.

These are not urgent matters but are included just to indicate the anomaly observed in #2 

Thank you.

**Comment by zacharee** [comment]
I don't think I'm going to add a single toggle for WiFi, because it's still pretty simple to tap two toggles instead of one.

1.11.0 has some logic to refresh the connected device data after saving WiFi settings, but you can also manually refresh on mobile by swiping down from the top of the app.

**Comment by ejgoldstick** [comment]
Thanks for following up... and I just installed the new version which works
on WIndows 11 perfectly (I'll do Android later):

The updated graph is great!   I'll try downloading a JSON file to see if I
can use the data natively myself, but the graph is a great tool. I agree
about not doing the single toggle... it probably would have been confusing
anyway.

Hint Control allowed me to test our Waveform antenna with the TMO-A4GR with
great satisfaction with the result.    I'd love to have something like
Speedtest integrated so that I could track throughput over time, but it's
not indispensable.   I don't know if it works with a lot of LTE/5G Internet
gateways,  but I'll let the Waveform people know...

Thanks!

Ed G.
