### ISSUE TITLE
Enhancement Requests: Add labels to the HINT main screen numbers, External access

### ISSUE THREAD

**Issue by pigs-on-the-wing** [zacharee/ArcadyanKVD21Control#59]
3 Questions ...

1. Would it possible to add the labels corresponding to the RSSI, RSRP, SINR values you are currently displaying in the main screen? It would be help to understand these numbers on a relative scale of 1-5 (V.Poor, Poor, Good, V.Good, Excellent)
See screenshot below for reference. 

2. Also, T-Mo does not list the RSSI value for 5G (neither in T-Mo HI app nor in T-Life app). Just curious as to where you are pulling these numbers from?

3. I have wifi mesh network behind the TMO HI gateway with external (internet) access to it. Would it possible to get ext access to Tmo gateway and control via HINT? Incredibly useful for managing parents internet device in case of issues

<img width="1130" alt="Screenshot 2024-07-17 at 8 52 36 AM" src="https://github.com/user-attachments/assets/49a0ae53-d4d9-4ae9-a97c-c7bd4f3e4ce4">

**Comment by zacharee** [comment]
I don't think there's much room for more labels, but I made the text colorful, along gradients from red to green depending on the current value and corresponding ranges:

<img width="912" alt="image" src="https://github.com/user-attachments/assets/6388502c-025f-45f1-9a69-74f22d1f8666">
___
The modem API returns an RSSI value for 5G. T-Mobile must just not be displaying it.
___
You can use something like [Meshnet](https://nordvpn.com/meshnet/), [Tailscale](https://tailscale.com/), or [ZeroTier](https://www.zerotier.com/) to set up a VPN that can traverse the T-Mobile NAT into the network to get remote access to the gateway. I'm not going to be making something like that for HINT Control.

**Comment by pigs-on-the-wing** [comment]
Awesome! Text colors are a better solution than what I'd proposed
I'll look further into the VPN angle for remote access

**Comment by pigs-on-the-wing** [comment]
Digit coloring looking nice. Thanks for implementing it. 
The colors are off currently (as in display Green for something that is poor should be red). 
Can you redo the color scaling to match the following ranges please or have gradual color scale please?

<img width="647" alt="Screenshot 2024-07-22 at 8 04 20 AM" src="https://github.com/user-attachments/assets/83b28b8c-02ae-4d13-a449-c139dec2dcc2">

**Comment by Ctyankee9** [comment]
![Screenshot_20240723_045947_HINT Control](https://github.com/user-attachments/assets/8b574f9d-b483-4622-ab69-cca70ffec1c0)

Question for the update. Status now equals CQI? Status used to be true/false and not listing a CQI now.
