### ISSUE TITLE
Reboot Gateway Failed

### ISSUE THREAD

**Issue by Chiefmoj0** [zacharee/ArcadyanKVD21Control#6]
Connected to the trashcan just fine, reboot button did not work. 
![Screenshot_20230601_184455_HINT Control~2](https://github.com/zacharee/ArcadyanKVD21Control/assets/135290883/79c86dff-a4d9-46d5-9e81-bdec0ddb49f6)

**Comment by zacharee** [comment]
This should be fixed in 1.3.0.

**Comment by Chiefmoj0** [comment]
Dig the app ✌️
