### ISSUE TITLE
Client List

### ISSUE THREAD

**Issue by Chiefmoj0** [zacharee/ArcadyanKVD21Control#7]
Trashcan-- Wired & Wireless inop

![Screenshot_20230601_221813_HINT Control~2](https://github.com/zacharee/ArcadyanKVD21Control/assets/135290883/724bc475-a9df-419a-b6d4-35a8d3777673)

**Comment by zacharee** [comment]
Go to the Settings tab and tap 10 times on the version number to enable the Fuzzer tab. Go to the Fuzzer tab and put `dashboard_device_info_status_web_app.cgi` in the "Url" field of the GET card and press "Run". 

Paste what it returns here.

**Comment by zacharee** [comment]
This should be fixed in 1.5.0.
