### ISSUE TITLE
Can you toggle Guest Mode on SSID2 on Nokia Gateway

### ISSUE THREAD

**Issue by LakeGuy1** [zacharee/ArcadyanKVD21Control#9]
Attached is a screenshot showing the grayed out Guest Mode toggle in the Network -> 2.4 GHz  using SSID2.
Can HINT  toggle this function ?

I am asking because I when I try to log in to Nokia Gateway with HINT, I get a socket timeout error. 
My gateway PW has  total of 8 LC, and Numbers . No special characters     
If HINT can not toggle Guest Mode, I do not need to solve login problem.
I can include all the various methods I have tried in a new issue if desired

**Comment by zacharee** [comment]
As far as I know, it isn't possible to toggle guest mode on the Nokia, so the switch is disabled.
